# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: myexample
before:
  hooks:
    - go mod download
    - go mod verify
builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - dockerfile: Dockerfile.scratch
    image_templates:
      - "metcalfc/myexample:{{ .Tag }}"
      - "metcalfc/myexample:v{{ .Major }}"
      - "metcalfc/myexample:v{{ .Major }}.{{ .Minor }}"
      - "metcalfc/myexample:latest"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{ .Version}}"
      - "--label=org.label-schema.name={{ .ProjectName}}"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit}}"
      - "--label=org.label-schema.vcs-url={{ .GitURL}}"
      - "--label=org.label-schema.build-date={{ .Date}}"
    binaries:
    - myexample
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
